/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./src/components/footer.vue')['default']
    Navbar: typeof import('./src/components/navbar.vue')['default']
    NavbarButton: typeof import('./src/components/navbar-button.vue')['default']
    ProjectItem: typeof import('./src/components/project-item.vue')['default']
    SectionHeader: typeof import('./src/components/section-header.vue')['default']
  }
}
